import Navbar from '@/components/navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Landing from '@/components/landing'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <div className="bg-white">
        <body className={inter.className}>
          <Navbar/>
          {children}
        </body>
      </div>
    </html>
  )
}
